In [1]:
import cv2


In [3]:
dirName = r'E:\Submission\WorkBranch\MCA-2021\sem_2\Image Processing\Jupyter File\Images'
image1 =dirName+'\Image3.jpg'
img = cv2.imread(image1,cv2.IMREAD_GRAYSCALE)


In [4]:
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Brightness

In [5]:
import numpy as np


image1 =dirName+'\Image3.jpg'
image = cv2.imread(image1)



In [6]:
Intensity_Matrix=np.ones(image.shape,dtype="uint8")*60

brt_image=cv2.add(image,Intensity_Matrix)
cv2.imshow("Bright",brt_image)
cv2.waitKey(0)


# print(Intensity_Matrix)

-1

In [7]:
dark_image=cv2.subtract(image,Intensity_Matrix)
cv2.imshow("dark",dark_image)
cv2.waitKey(0)
print(Intensity_Matrix)

[[[60 60 60]
  [60 60 60]
  [60 60 60]
  ...
  [60 60 60]
  [60 60 60]
  [60 60 60]]

 [[60 60 60]
  [60 60 60]
  [60 60 60]
  ...
  [60 60 60]
  [60 60 60]
  [60 60 60]]

 [[60 60 60]
  [60 60 60]
  [60 60 60]
  ...
  [60 60 60]
  [60 60 60]
  [60 60 60]]

 ...

 [[60 60 60]
  [60 60 60]
  [60 60 60]
  ...
  [60 60 60]
  [60 60 60]
  [60 60 60]]

 [[60 60 60]
  [60 60 60]
  [60 60 60]
  ...
  [60 60 60]
  [60 60 60]
  [60 60 60]]

 [[60 60 60]
  [60 60 60]
  [60 60 60]
  ...
  [60 60 60]
  [60 60 60]
  [60 60 60]]]


### Split the image in to R,G,B

In [8]:
RGBPath =dirName+'\RGB.png'
imageRGB = cv2.imread(RGBPath)

In [9]:
cv2.imshow("Original_image",imageRGB)
cv2.waitKey(0)


b,g,r=cv2.split(imageRGB)

In [19]:
cv2.imshow("Red",r)
cv2.waitKey(0)

-1

In [ ]:
cv2.imshow("Blue",b)
cv2.waitKey(0)

In [20]:
cv2.imshow("Green",g)
cv2.waitKey(0)

-1

### Pending

### Rotate 60 degree


In [11]:
import imutils

image1 =dirName+'\Image3.jpg'
img = cv2.imread(image1,cv2.IMREAD_COLOR)
rotate_img = imutils.rotate(img,angle=60)
cv2.imshow("Rotated",rotate_img)
cv2.waitKey(0)

-1

### Transition

In [14]:
image1 =dirName+'\Image3.jpg'
img = cv2.imread(image1,cv2.IMREAD_COLOR)
height, width = img.shape[:2]
quarter_height, quarter_width = height / 4, width / 4
T = np.float32([[1, 0, quarter_width], [0, 1, quarter_height]])
img_translation = cv2.warpAffine(img, T, (width, height))


In [15]:
cv2.imshow("Originalimage", img)
cv2.waitKey()
cv2.destroyAllWindows()

In [16]:
cv2.imshow('Translation', img_translation)
cv2.waitKey()
cv2.destroyAllWindows()